version: "3.3"
services:
  db:
    container_name: mysql_db
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: srvcontdemo123& # This root password is only intended for local development & build pipeline, do not use it elsewhere
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
