name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  test-and-build-api:
    runs-on: ubuntu-latest
    name: Test and Build API

    defaults:
      run:
        working-directory: ./api

    services:
      # MySQL container
      mysql_db:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: srvcontdemo123& # This root password is only intended for local development & build pipeline, do not use it elsewhere
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 2s
          --health-timeout 1s
          --health-retries 30

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install dependencies of API"
        run: yarn install

      # Unit Test
      - name: "Unit Test API"
        run: yarn test:cov --reporters=default --reporters=jest-html-reporter
      - name: Publish unit test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: ./api/test-report.html
      - name: Publish unit test code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-code-coverage-results
          path: ./api/coverage/clover.xml

      # E2E Test
      - name: "Create and migrate test database"
        run: yarn ensure-test-db
      - name: "E2E Test API"
        run: yarn test:e2e --reporters=default --reporters=jest-html-reporter
      - name: Publish e2e test results
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-results
          path: ./api/test-report.html

      # Build
      - name: "Build distributable release version of API"
        run: yarn build
      - name: Publish distributable
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./api/dist/
